### ISSUE TITLE
Move settings to .env

### ISSUE THREAD

**Issue by rizqirizqi** [rizqirizqi/scientific-name-fetcher#4]
The current settings are hardcoded in the `main.py` file. It's better to move it to `.env` file. We can use `python-dotenv` to make it easier.

**Comment by edcolvin** [comment]
I will submit a pull request for this. 

Dotenv file only handles string values. Right now there are two boolean variables that seem like they should be moved: WITH_GBIF_SEARCH and AUTO_SEARCH_PREDICTED_SPECIES.

It seems like the variable should be set to True if the settings value is "True" (case insensitive). That's how I will set it up. Let me know if you would prefer some other behavior, and I will submit another pull request.

I have a couple of suggestions, as well. First, what would you think of using a  filename other than  .env, so it wouldn't be hidden by default in Unix shells?

Also, I would recommend using the configparser module from the standard library, instead of dotenv. 
Because it's in the standard lib, there is one less dependency to break or cause problems down the line. Also, it has a convention for dealing with boolean types, that has some flexibility, allowing things like '1/0', 'yes/no', 'true/false'. I can submit a pull request for this, too, if you'd like to see it.

**Comment by rizqirizqi** [comment]
Hi @edcolvin, looks like your suggestion is good so that we don't need to add more dependency and it has a convention for dealing with boolean types. However, @hgb123 has already submitted a PR for this issue (although it's submitted after your comment to work on this issue). Are you still working on this?

What do you guys think? Is it better to use `python-dotenv` or `configparser`?

P.S. Actually I didn't expect to get a PR on my repo this fast, maybe it happened because of the Hacktoberfest event. Lol.
